name: build

on:
  create:
    tags:
    - '*'
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - uses: subosito/flutter-action@v1.3.2
      with:
        flutter-version: '1.19.0-1.0.pre'
        channel: 'dev'
    - name: enable desktop
      run: |
        flutter  config --enable-macos-desktop
#        flutter  config --enable-linux-desktop
#        flutter  config --enable-windows-desktop
#        flutter  config --enable-web
    - run: flutter pub get
    - run: flutter doctor -v
    - name: env init
      run: |
        sed -i "" "s/KEY_PASSWORD/${{ secrets.KEY_PASSWORD }}/g" android/key.properties
        sed -i "" "s/STORE_PASSWORD/${{ secrets.STORE_PASSWORD }}/g" android/key.properties
        echo "${{ secrets.PLAY_STORE_UPLOAD_KEY }}" | base64 --decode > android/key.jks
    - name: Setup Go environment
      uses: actions/setup-go@v2.0.3
      with:
        go-version: 1.14.1
        stable: true 
    - run: go version
    - run: GO111MODULE=on go get -u -a github.com/go-flutter-desktop/hover
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@0.0.1
      with:
        # Docker Version
        docker_version: 19.03  #optional, default is 19.03
        # Docker Channel
        docker_channel: stable  # optional, default is stable
    - run: hover build darwin-dmg
    - run: flutter build apk
    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.TOKEN }}

